//Errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Staff
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const LOAD_LOGGED_IN_CUSTOMER = "LOAD_LOGGED_IN_CUSTOMER";

