//Errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Customer
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const LOAD_LOGGED_IN_CUSTOMER = "LOAD_LOGGED_IN_CUSTOMER";
export const UPDATE_SHOPPING_CART_ITEMS_STOCK = "UPDATE_SHOPPING_CART_ITEMS_STOCK";

//Product Variant
export const ALL_SKU = "ALL_SKU";
export const DISPLAY_PRODUCT_VARIANT = "DISPLAY_PRODUCT_VARIANT";
export const DISPLAY_STOCKS = "DISPLAY_STOCKS";

//Transaction
export const UPDATE_VIEWED_TXN = "UPDATE_VIEWED_TXN";
export const RETRIEVE_TXNS = "RETRIEVE_TXNS";

//Reservation
export const RETRIEVE_UPCOMING_RESERVATIONS = "RETRIEVE_UPCOMING_RESERVATIONS";
export const RETRIEVE_PAST_RESERVATIONS = "RETRIEVE_PAST_RESERVATIONS";
export const UPDATE_VIEWED_RESERVATION = "UPDATE_VIEWED_RESERVATION";
