// Customer
export const CREATE_NEW_CUSTOMER = "CREATE_NEW_CUSTOMER";
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";
export const RESET_VERIFICATION_STATUS = "RESET_VERIFICATION_STATUS";
export const EMAIL_SENDING = "EMAIL_SENDING";
export const EMAIL_SENT = "EMAIL_SENT";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

//Address
export const UPDATE_SHIPPING_ADDRESS_SUCCESS = "UPDATE_SHIPPING_ADDRESS_SUCCESS";

// Error
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Category
export const RETRIEVE_ROOT_CATEGORIES = "RETRIEVE_ROOT_CATEGORIES";

//Contact Us
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";
export const RETRIEVE_ALL_CONTACT_US_CATEGORY_ENUM_SUCCESS =
  "RETRIEVE_ALL_CONTACT_US_CATEGORY_ENUM_SUCCESS";

//Products
export const DISPLAY_PRODUCTS = "DISPLAY_PRODUCTS";
