// Customer
export const CREATE_NEW_CUSTOMER = "CREATE_NEW_CUSTOMER";
export const CUSTOMER_LOGIN = "CUSTOMER_LOGIN";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILURE = "VERIFY_FAILURE";
export const RESET_VERIFICATION_STATUS = "RESET_VERIFICATION_STATUS";
export const EMAIL_SENDING = "EMAIL_SENDING";
export const EMAIL_SENT = "EMAIL_SENT";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

// Error
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Category
export const RETRIEVE_ROOT_CATEGORIES = "RETRIEVE_ROOT_CATEGORIES";

//Contact Us
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";
export const RETRIEVE_ALL_CONTACT_US_CATEGORY_ENUM_SUCCESS =
  "RETRIEVE_ALL_CONTACT_US_CATEGORY_ENUM_SUCCESS";

//Products
export const DISPLAY_PRODUCTS = "DISPLAY_PRODUCTS";

//Shopping cart
export const UPDATE_SHOPPING_CART_SUCCESS = "UPDATE_SHOPPING_CART_SUCCESS";

//Tags
export const RETRIEVE_ALL_TAGS = "RETRIEVE_ALL_TAGS";

//FILTER BAR
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const SET_CHECKED_COLOURS = "SET_CHECKED_COLOURS";
export const SET_CHECKED_SIZES = "SET_CHECKED_SIZES";
export const SET_CHECKED_TAGS = "SET_CHECKED_TAGS";
export const SET_SELECTED_SORT = "SET_SELECTED_SORT";
