// General
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_ERRORS = "UPDATE ERRORS";

// Store
export const CREATE_STORE = "CREATE_STORE";
export const RETRIEVE_STORE = "RETRIEVE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const RETRIEVE_ALL_STORES = "RETRIEVE_ALL_STORES";
export const DELETE_STORE = "DELETE_STORE";
export const CLEAR_CURRENT_STORE = "CLEAR_CURRENT_STORE";

// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCT_BY_ID = "RETRIEVE_PRODUCT_BY_ID";
export const RETRIEVE_ALL_PRODUCTS = "RETRIEVE_ALL_PRODUCTS";

// Tag
export const CREATE_TAG = "CREATE_TAG";
export const RETRIEVE_ALL_TAGS = "RETRIEVE_ALL_TAGS";
