// General
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_ERRORS = "UPDATE ERRORS";

// Store
export const CREATE_STORE = "CREATE_STORE";
export const RETRIEVE_STORE = "RETRIEVE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const RETRIEVE_ALL_STORES = "RETRIEVE_ALL_STORES";
export const DELETE_STORE = "DELETE_STORE";
export const CLEAR_CURRENT_STORE = "CLEAR_CURRENT_STORE";

// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCT_BY_ID = "RETRIEVE_PRODUCT_BY_ID";
export const RETRIEVE_ALL_PRODUCTS = "RETRIEVE_ALL_PRODUCTS";
export const RETRIEVE_PRODUCTS_DETAILS = "RETRIEVE_PRODUCTS_DETAILS";

// Tag
export const CREATE_TAG = "CREATE_TAG";
export const RETRIEVE_ALL_TAGS = "RETRIEVE_ALL_TAGS";
export const RETRIEVE_TAG = "RETRIEVE_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const ADD_TAG_TO_PRODUCTS = "ADD_TAG_TO_PRODUCTS";

// Category
export const RETRIEVE_ALL_ROOT_CATEGORIES = "RETRIEVE_ALL_ROOT_CATEGORIES";
export const RETRIEVE_ALL_CATEGORIES = "RETRIEVE_ALL_CATEGORIES";
export const RETRIEVE_ALL_PRODUCTS_FOR_CATEGORY =
  "RETRIEVE_ALL_PRODUCTS_FOR_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// Staff
export const CHANGE_STAFF_PASSWORD = "CHANGE_STAFF_PASSWORD";
export const STAFF_LOGIN = "STAFF_LOGIN";
//For HR only
export const RETRIEVE_ALL_STAFF = "RETRIEVE_ALL_STAFF";
export const CREATE_STAFF = "CREATE_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
export const RETRIEVE_STAFF = "RETRIEVE_STAFF";
//For admin/IT only
export const CREATE_STAFF_ACCOUNT = "CREATE_STAFF_ACCOUNT";
export const RESET_STAFF_PASSWORD = "RESET_STAFF_PASSWORD";
