// General
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATE_ERRORS = "UPDATE ERRORS";

// Login
export const RETRIEVE_STORE_LOGIN = "RETRIEVE_STORE_LOGIN";

// Store
export const CREATE_STORE = "CREATE_STORE";
export const RETRIEVE_STORE = "RETRIEVE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const RETRIEVE_ALL_STORES = "RETRIEVE_ALL_STORES";
export const DELETE_STORE = "DELETE_STORE";
export const CLEAR_CURRENT_STORE = "CLEAR_CURRENT_STORE";

// Product
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCT_BY_ID = "RETRIEVE_PRODUCT_BY_ID";
export const RETRIEVE_ALL_PRODUCTS = "RETRIEVE_ALL_PRODUCTS";
export const RETRIEVE_PRODUCTS_DETAILS = "RETRIEVE_PRODUCTS_DETAILS";

// Tag
export const CREATE_TAG = "CREATE_TAG";
export const RETRIEVE_ALL_TAGS = "RETRIEVE_ALL_TAGS";
export const RETRIEVE_TAG = "RETRIEVE_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const DELETE_TAG = "DELETE_TAG";
export const ADD_TAG_TO_PRODUCTS = "ADD_TAG_TO_PRODUCTS";
export const DELETE_TAG_FROM_PRODUCTS = "DELETE_TAG_FROM_PRODUCTS";

// Category
export const RETRIEVE_ALL_ROOT_CATEGORIES = "RETRIEVE_ALL_ROOT_CATEGORIES";
export const RETRIEVE_ALL_CATEGORIES = "RETRIEVE_ALL_CATEGORIES";
export const RETRIEVE_ALL_PRODUCTS_FOR_CATEGORY =
  "RETRIEVE_ALL_PRODUCTS_FOR_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

// Staff
export const CHANGE_STAFF_PASSWORD = "CHANGE_STAFF_PASSWORD";
export const STAFF_LOGIN = "STAFF_LOGIN";
export const STAFF_LOGOUT = "STAFF_LOGOUT";
export const UPDATE_STAFF = "UPDATE_STAFF";
export const RETRIEVE_ROLE = "RETRIEVE_ROLE";
export const RETRIEVE_DEPARTMENT = "RETRIEVE_DEPARTMENT";
export const RETRIEVE_ADDRESS = "RETRIEVE_ADDRESS";
//For HR only
export const RETRIEVE_ALL_STAFF = "RETRIEVE_ALL_STAFF";
export const CREATE_STAFF = "CREATE_STAFF";
export const DELETE_STAFF = "DELETE_STAFF";
export const RETRIEVE_STAFF = "RETRIEVE_STAFF";
export const RETRIEVE_ALL_ROLES = "RETRIEVE_ALL_ROLES";
export const RETRIEVE_ALL_DEPARTMENTS = "RETRIEVE_ALL_DEPARTMENTS";
//For admin/IT only
export const CREATE_STAFF_ACCOUNT = "CREATE_STAFF_ACCOUNT";
export const RETRIEVE_STAFF_WITH_NO_ACCOUNT = "RETRIEVE_STAFF_WITH_NO_ACCOUNT";
export const RESET_STAFF_PASSWORD = "RESET_STAFF_PASSWORD";
// ProductStock
export const UPDATE_PRODUCT_STOCK = "UPDATE_PRODUCT_STOCK";
export const UPDATE_PRODUCT_STOCK_QTY = "UPDATE_PRODUCT_STOCK_QTY";
export const RETRIEVE_PRODUCT_STOCKS_BY_PARAMETER =
  "RETRIEVE_PRODUCT_STOCKS_BY_PARAMETER";
export const SIMULATE_REORDERING_FROM_SUPPLIER = "SIMULATE_REORDERING_FROM_SUPPLIER";
