//Errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//Staff
export const STAFF_LOGIN = "STAFF_LOGIN";
export const STAFF_LOGOUT = "STAFF_LOGOUT";
export const LOAD_LOGGED_IN_STAFF = "LOAD_LOGGED_IN_STAFF";

//Product Variant
export const ALL_SKU = "ALL_SKU";
export const DISPLAY_PRODUCT_VARIANT = "DISPLAY_PRODUCT_VARIANT";
export const DISPLAY_STOCKS = "DISPLAY_STOCKS";

//ReservationDetail
export const DISPLAY_UPCOMING_RESERVATIONS = "DISPLAY_UPCOMING_RESERVATIONS";
export const DISPLAY_RESERVATION = "DISPLAY_RESERVATION";

